name: Release to Docker

# Controls when the action will run.
on:
  workflow_dispatch:
  push:
    # only publish on version tags
    branches:
      - 'release'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
            ~/bin/protoc
            ~/.cache
          key: ${{ runner.os }}-recorder-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-recorder

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-recorder-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-recorder-modules

      - name: Docker metadata
        id: docker-md
        uses: docker/metadata-action@v3
        with:
          images: dunkbing/meeting-bot
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Download Go modules
        run: go mod download

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          docker build -t dunkbing/meeting-bot:latest -f build/Dockerfile .
          docker push dunkbing/meeting-bot:latest
